# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

# This workflow will run on every push or pull request to the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs
jobs:
  build:
    # Specify the OS the workflow will run on
    runs-on: ubuntu-latest

    # Define the steps to execute
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can specify the version you need, e.g., 16 or 18

      # Install dependencies using npm
      - name: Install dependencies
        run: npm install

      # Optionally, you can build your application if needed
      - name: Build application
        run: npm run build  # Assumes you have a build script in your package.json

     

